### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by Birdman86** [fondberg/easee_hass#314]
### The problem

I keep getting this error in the logg and it loses connection to the charger even though it shows the states as available.
Sometimes it will show the charger as off even though it is on and the power sensor is showing power usage...
What is causing this?

### Version of Easee integration having the issue?

0.9.50

### Version of Home Assistant Core having the issue?

2023.4.6

### Anything in the logs that might be useful for us?

```txt
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/easee/const.py:397
Integration: easee (documentation, issues)
First occurred: 10:53:30 (256 occurrences)
Last logged: 10:54:26

Update for sensor.[xxx]_equalizer_limit fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/easee/entity.py", line 260, in async_update
    self._state = self._state_func(self.data.state)
  File "/config/custom_components/easee/const.py", line 397, in <lambda>
    state["eqAvailableCurrentP1"],
  File "/usr/local/lib/python3.10/site-packages/pyeasee/utils.py", line 55, in __getitem__
    if type(self._storage[key]) == str and validate_iso8601(self._storage[key]):
KeyError: 'eqAvailableCurrentP1'
```

**Comment by olalid** [comment]
Seems like some data is missing, which causes the integration to fail...
Do you have an equalizer in your setup?

I guess we need to look in to solving this issue that missing data causes so much problems, this should be handled better...

**Comment by olalid** [comment]
This PR should remove the error message from the log at least.
https://github.com/fondberg/easee_hass/pull/322

**Comment by olalid** [comment]
Please test the latest release and let us know if it solves your problems.

**Comment by Birdman86** [comment]
No, I don't have an Equalizer, as that stuff is handled by tibber.

Yeah, running latest HA and easee, but still get the error...

I guess that as I don't use an Easee Equalizer, it is trying to pull data where there is none...
I just disabled that specific equalizer sensor now to not get the error.

**Comment by olalid** [comment]
Did you test with the latest version that v0.9.52 that we released about 1 hour ago?

**Comment by Birdman86** [comment]
No, sorry, I just got the update notification.
Let me check.

**Comment by Birdman86** [comment]
Yes, it seems to have fixed the issue.
Still not getting any data from the equalizer sensor but I guess it is because of missing service, which is expected.

**Comment by olalid** [comment]
Yes, there is nothing we can do about that data is missing, but at least avoid having log cluttered with errors...
Thanks for verifying.
